{ self, username, ... }:
{
  flake.nixosModules.ryujinxCanary =
    { config, lib, pkgs, ... }:
    let
      cfg = config.hostConfig.emulators.ryujinx;

      emu = "/mnt/media/Games/Emulation";
      romsDir = "${emu}/Roms/nintendo-switch";

      ryujinxGameMode = pkgs.writeShellScriptBin "ryujinx-gamemode" ''
        # Avalonia picks Wayland when WAYLAND_DISPLAY is set and renders straight
        # to gamescope-0, which Gaming Mode's X11-only focus handoff never tracks
        # (tile stuck "Launching"). Hide the Wayland socket so it falls back to
        # the :1 XWayland Gaming Mode focuses — same rationale as the Chromium
        # --ozone-platform=x11 tile. Verify on-device.
        unset WAYLAND_DISPLAY
        exec ${cfg.package}/bin/ryujinx-canary "$@"
      '';

      # Config.json seed. A PARTIAL config is fatal: Ryujinx accepts it (no
      # *.invalid rename) but then NREs in ConfigurationState.Load when a
      # reactive handler fires on a field the partial config omitted (verified
      # on-device: LoggerModule crash -> tile does nothing). So the seed must be
      # a COMPLETE config. ryujinx-config-seed.json is a full default Config.json
      # generated by Ryujinx Canary 1.3.334 (config `version` 73) with its dir
      # lists blanked; we fill them here so the /mnt/media base lives in one
      # place. game_dirs = rom scan dirs; autoload_dirs = DLC + title updates
      # (one list, both). Seed applies on first run only (activation writes if
      # absent); a newer Canary migrates it on load. If a schema bump ever
      # rejects it, regenerate the template from a fresh Config.json.
      configSeed = pkgs.writeText "ryujinx-config-seed.json" (
        builtins.toJSON (
          (builtins.fromJSON (builtins.readFile ./ryujinx-config-seed.json))
          // {
            game_dirs = [ romsDir ];
            autoload_dirs = [
              "${emu}/DLC/nintendo-switch"
              "${emu}/Updates/nintendo-switch"
            ];
          }
        )
      );
    in
    {
      # Repo standard: importing a module enables it — no enable flag.
      options.hostConfig.emulators.ryujinx = {
        package = lib.mkOption {
          type = lib.types.package;
          default = self.packages.${pkgs.stdenv.hostPlatform.system}.ryujinx-canary;
          defaultText = lib.literalExpression "self.packages.<system>.ryujinx-canary";
          description = "Pinned Ryujinx Canary package (built in modules/packages/ryujinx-canary.nix).";
        };
      };

      config = {
        environment.systemPackages = [ cfg.package ];

        # Game Mode Tile; importing this module requires the steamShortcuts
        # module on the same host (see docs/adr/0003).
        hostConfig.steamShortcuts.shortcuts.Ryujinx = {
          exe = "${ryujinxGameMode}/bin/ryujinx-gamemode";
          icon = "${cfg.package}/share/icons/hicolor/256x256/apps/ryujinx-canary.png";
          # Avalonia emulator UI. If it hangs before mapping a window under the
          # Steam overlay LD_PRELOAD like LibreWolf/Jellyfin did, set
          # allowOverlay = false here — left on for now since the overlay is
          # useful in-game. Verify on-device.
        };

        home-manager.users.${username} =
          { config, lib, ... }:
          {
            # Only the Ryujinx-managed dirs are redirected. Saves live under
            # <base>/bis/user/save; keys under <base>/system. Roms/DLC/Updates are
            # NOT stored by Ryujinx — it references them by path (see configSeed).
            #
            # Saves -> shared NFS media. NOTE: both hosts point at the SAME save
            # tree, so don't run the same title on both hosts at once (clobber).
            home.file.".config/Ryujinx/bis/user/save".source =
              config.lib.file.mkOutOfStoreSymlink "${emu}/Saves/nintendo-switch/ryujinx";

            # prod.keys/title.keys shared across hosts via the media BIOS dir.
            # Firmware is installed in-app per host (Tools > Install Firmware,
            # from ${emu}/BIOS/nintendo-switch/firmware).
            home.file.".config/Ryujinx/system".source =
              config.lib.file.mkOutOfStoreSymlink "${emu}/BIOS/nintendo-switch";

            # Seed Config.json once; Ryujinx owns it after first launch (it
            # rewrites the file on exit, so we must not manage it as a read-only
            # store symlink). Only writes if absent.
            home.activation.ryujinxSeedConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
              cfg="$HOME/.config/Ryujinx/Config.json"
              if [ ! -e "$cfg" ]; then
                run mkdir -p "$HOME/.config/Ryujinx"
                run install -m600 ${configSeed} "$cfg"
              fi
            '';
          };
      };
    };
}
